typedef enum Error {
    SUCCESSFUL,
    SDL_INITIALIZATION_FAILED,
    SDL_WINDOW_CREATION_FAILED,
    SDL_RENDERER_CREATION_FAILED,
    SDL_DRAW_COLOR_SETTING_FAILED,
    SDL_CLEARING_FAILED,
    
} Error;
